# Introduction to qiskit_qcsg_extensions
- 간단히 말하자면 기존의 qiskit 모듈의 기본 기능을 더 손쉽게 사용하기 위한 qiskit의 확장 라이브러리
- 오늘은 양자상태 객체 정의와 기본 속성, 메소드를 실행하는 예제 데모 수행

# 기존 라이브러리 사용 에시

In [23]:
# importing module
from qiskit.quantum_info import Statevector

In [37]:
# define a statevector
# plus = Statevector.from_label('+')
Statevector.from_label('+')

Statevector([0.70710678+0.j, 0.70710678+0.j],
            dims=(2,))


In [30]:
# print the statevector in latex
Statevector.from_label('+').draw('latex')

<IPython.core.display.Latex object>

In [32]:
# returns the statevector amplitues as a numpy array
Statevector.from_label('+').data

array([0.70710678+0.j, 0.70710678+0.j])

# qiskit_qcsg_extensions 사용 예시 
- 위 예제와 동일 상태, 동일 출력 수행

In [33]:
# importing module
from qiskit_qcsg_extensions import Qubit

In [38]:
# define a state vector, or qubit state
# plus = Qubit('+')
Qubit('+')

Statevector([0.70710678+0.j, 0.70710678+0.j],
            dims=(2,))


In [40]:
# print the statevector in latex
Qubit('+').latex

<IPython.core.display.Latex object>

In [41]:
# returns the state's amplitues as a numpy array
Qubit('+').amplitudes

array([0.70710678+0.j, 0.70710678+0.j])

In [42]:
Qubit('+').df

amplitudes  probabilities
basis                                   
|0>    0.707107+0.000000j            0.5
|1>    0.707107+0.000000j            0.5

# (class) Qubit

In [2]:
Qubit('0'), Qubit('1'), Qubit('+'), Qubit('-')

(<qiskit_qcsg_extensions.qubit.Qubit at 0x12ff47150>,
 <qiskit_qcsg_extensions.qubit.Qubit at 0x15e72e010>)

In [3]:
state_zero = Qubit('0')
state_zero

Statevector([1.+0.j, 0.+0.j],
            dims=(2,))


# (attributes) <_Qubit_>.attribute
### - <_Qubit_>.label 
### - <_Qubit_>.amplitudes 
### - <_Qubit_>.probabilities 
### - <_Qubit_>.df
### - <_Qubit_>.basis_label
### - <_Qubit_>.basis 

In [4]:
dir(Qubit('+'))

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 'amplitudes',
 'basis',
 'basis_label',
 'df',
 'get_amplitudes',
 'get_df',
 'get_probabilities',
 'label',
 'latex',
 'probabilities',
 'show_latex',
 'state']

In [5]:
state_zero.label

'0'

In [6]:
state_zero.latex

<IPython.core.display.Latex object>

In [7]:
state_zero.amplitudes

array([1.+0.j, 0.+0.j])

In [8]:
state_zero.probabilities

array([1., 0.])

In [9]:
state_zero.df

amplitudes  probabilities
basis                           
|0>      1.0+0.0j            1.0
|1>      0.0+0.0j            0.0

# (methods) <_Qubit_>.method()
### - <_Qubit_>.method() == <_Statevector.from_label()_>.method()

In [14]:
Qubit('+').latex

<IPython.core.display.Latex object>

In [17]:
Qubit('+').df

amplitudes  probabilities
basis                                   
|0>    0.707107+0.000000j            0.5
|1>    0.707107+0.000000j            0.5

In [5]:
Qubit('0').latex

<IPython.core.display.Latex object>

In [44]:
dir(Qubit('+'))

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 'amplitudes',
 'basis',
 'basis_label',
 'df',
 'get_amplitudes',
 'get_df',
 'get_probabilities',
 'label',
 'latex',
 'probabilities',
 'show_latex',
 'state']