In [1]:
from qiskit_qcsg_extensions import Qubit

# (class) Qubit

In [2]:
Qubit('0'), Qubit('1'), Qubit('+'), Qubit('-')

(<qiskit_qcsg_extensions.qubit.Qubit at 0x12ff47150>,
 <qiskit_qcsg_extensions.qubit.Qubit at 0x15e72e010>)

In [3]:
state_zero = Qubit('0')
state_zero

Statevector([1.+0.j, 0.+0.j],
            dims=(2,))


# (attributes) <_Qubit_>.attribute
### - <_Qubit_>.label 
### - <_Qubit_>.amplitudes 
### - <_Qubit_>.probabilities 
### - <_Qubit_>.df
### - <_Qubit_>.basis_label
### - <_Qubit_>.basis 

In [4]:
dir(Qubit('+'))

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 'amplitudes',
 'basis',
 'basis_label',
 'df',
 'get_amplitudes',
 'get_df',
 'get_probabilities',
 'label',
 'latex',
 'probabilities',
 'show_latex',
 'state']

In [5]:
state_zero.label

'0'

In [6]:
state_zero.latex

<IPython.core.display.Latex object>

In [7]:
state_zero.amplitudes

array([1.+0.j, 0.+0.j])

In [8]:
state_zero.probabilities

array([1., 0.])

In [9]:
state_zero.df

amplitudes  probabilities
basis                           
|0>      1.0+0.0j            1.0
|1>      0.0+0.0j            0.0

# (methods) <_Qubit_>.method()
### - <_Qubit_>.method() == <_Statevector.from_label()_>.method()

In [14]:
Qubit('+').latex

<IPython.core.display.Latex object>

In [17]:
Qubit('+').df

amplitudes  probabilities
basis                                   
|0>    0.707107+0.000000j            0.5
|1>    0.707107+0.000000j            0.5

In [5]:
Qubit('0').latex

<IPython.core.display.Latex object>

In [2]:
Ket('+').latex

<IPython.core.display.Latex object>

In [3]:
Ket('+').basis

[np.str_('0'), np.str_('1')]

In [4]:
Ket('00').latex

<IPython.core.display.Latex object>

In [12]:
Ket('+++').latex

<IPython.core.display.Latex object>

In [18]:
Ket('0').latex

<IPython.core.display.Latex object>

In [21]:
Ket('0').conjugate()

Statevector([1.-0.j, 0.-0.j],
            dims=(2,))


In [24]:
Statevector.from_label('0').conjugate().draw('latex')

<IPython.core.display.Latex object>

In [12]:
dct = Ket('00').state.probabilities_dict()
dct

{np.str_('00'): np.float64(1.0)}

In [13]:
basis = list(dct.keys())
basis

[np.str_('00')]

In [14]:
amplitudes = list(Ket('00').state.data)
amplitudes

[np.complex128(1+0j), np.complex128(0j), np.complex128(0j), np.complex128(0j)]

In [15]:
probabilities = list(Ket('00').state.probabilities())
probabilities

[np.float64(1.0), np.float64(0.0), np.float64(0.0), np.float64(0.0)]

In [16]:
data = {'basis': basis, 'amplitudes': amplitudes, 'probabilities': probabilities}
data

{'basis': [np.str_('00')],
 'amplitudes': [np.complex128(1+0j),
  np.complex128(0j),
  np.complex128(0j),
  np.complex128(0j)],
 'probabilities': [np.float64(1.0),
  np.float64(0.0),
  np.float64(0.0),
  np.float64(0.0)]}

In [17]:
df = pd.DataFrame(data).set_index('basis')
df

ValueError: All arrays must be of the same length

In [26]:
Statevector.from_int(0, 3)

Statevector([1.+0.j, 0.+0.j, 0.+0.j],
            dims=(3,))


In [2]:
ket_plus = Qubit(label='+')

In [4]:
ket_plus.latex

<IPython.core.display.Latex object>

In [7]:
ket_plus.amplitudes

array([0.70710678+0.j, 0.70710678+0.j])

In [6]:
ket_plus.probabilities

array([0.5, 0.5])

In [3]:
ket_plus.df

amplitudes  probabilities
basis                                   
0      0.707107+0.000000j            0.5
1      0.707107+0.000000j            0.5

In [16]:
Statevector.from_label('+')

Statevector([0.70710678+0.j, 0.70710678+0.j],
            dims=(2,))


In [17]:
Statevector.from_label('+').conjugate()

Statevector([0.70710678-0.j, 0.70710678-0.j],
            dims=(2,))


In [22]:
Statevector.from_label('-').to_operator().draw('latex')

<IPython.core.display.Latex object>

AttributeError: 'Qubit' object has no attribute 'data'

In [8]:
dir(Statevector)

['_ATOL_DEFAULT',
 '_MAX_TOL',
 '_RTOL_DEFAULT',
 '__abstractmethods__',
 '__add__',
 '__and__',
 '__array__',
 '__array_priority__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmul__',
 '__setattr__',
 '__sizeof__',
 '__slotnames__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__weakref__',
 '__xor__',
 '_abc_impl',
 '_add',
 '_evolve_instruction',
 '_evolve_operator',
 '_expectation_value_pauli',
 '_index_to_ket_array',
 '_ipython_display_',
 '_matrix_to_dict',
 '_multiply',
 '_rng',
 '_subsystem_probabilities',
 '_vector_to_dict',
 'atol',
 'conjugate',
 'copy',
 'data',
 'dim',
 'dims',
 'draw',
 'equiv',
 'evolve',
 'expand',
 'expecta

In [17]:
dct = ket_plus.get_info()
dct

{np.str_('0'): np.float64(0.4999999999999999),
 np.str_('1'): np.float64(0.4999999999999999)}

In [36]:
amplitudes = ket_plus.amplitudes
amplitudes

array([0.70710678+0.j, 0.70710678+0.j])

In [43]:
pd.DataFrame(columns=['probability', 'amplitudes'], index=[list(dct.keys())])

probability amplitudes
0         NaN        NaN
1         NaN        NaN

In [50]:
df = pd.DataFrame(data={'amplitude': ket_plus.amplitudes, 'probability': dct.values()}, index=list(dct.keys()))
df.index.name = 'basis'
df

amplitude  probability
basis                                 
0      0.707107+0.000000j          0.5
1      0.707107+0.000000j          0.5

In [41]:
df = pd.DataFrame(columns=list(dct.keys()), data=[dct.values(), amplitudes], index=['probability', 'amplitudes'])
df.columns.name = 'basis'
df

basis                         0                   1
probability  0.500000+0.000000j  0.500000+0.000000j
amplitudes   0.707107+0.000000j  0.707107+0.000000j

In [28]:
pd.DataFrame([dct])    


0    1
0  0.5  0.5

In [13]:
ket_plus.amplitudes

array([0.70710678+0.j, 0.70710678+0.j])

In [5]:
ket_plus = Ket(qubits=Qubit('+'))

In [6]:
ket_plus = Ket('+') 

In [7]:
ket_plus.qubits

In [11]:
ket_plus.qubits[0].latex

<IPython.core.display.Latex object>

In [3]:
ket_plus.latex

<IPython.core.display.Latex object>

In [7]:
ket_plus.data

array([0.70710678+0.j, 0.70710678+0.j])

In [8]:
ket_plus.state

Statevector([0.70710678+0.j, 0.70710678+0.j],
            dims=(2,))
