In [3]:
from qiskit.quantum_info import Statevector, Operator
from numpy import sqrt

In [4]:
zero_list = [0] * (2 ** 3)
zero_list

[0, 0, 0, 0, 0, 0, 0, 0]

In [5]:
zero_list[0] = 1
zero_list

[1, 0, 0, 0, 0, 0, 0, 0]

In [18]:
zero_list = [0] * (2 ** 3)
zero_list[3] = 1
Statevector(zero_list).draw('latex')

<IPython.core.display.Latex object>

In [21]:
zero_list = [0] * (2 ** 3)
zero_list[1] = 1
zero_list[2] = 1
zero_list[4] = 1
W = Statevector(zero_list / sqrt(3)) 
W.draw('latex')

<IPython.core.display.Latex object>

In [38]:
result_of_measurement, state_collapsed = W.measure([1])

In [39]:
result_of_measurement

np.str_('0')

In [40]:
state_collapsed.draw('latex')

<IPython.core.display.Latex object>

# Draw Bell states

In [45]:
ket_0zero_1zero = Statevector.from_label('00')
ket_0one_1one = Statevector.from_label('11')

In [46]:
ket_0zero_1zero.draw('latex')

<IPython.core.display.Latex object>

In [47]:
ket_0one_1one.draw('latex')

<IPython.core.display.Latex object>

In [61]:
ket_bell_first = 1/sqrt(2)*(Statevector.from_label('00') + Statevector.from_label('11'))
ket_bell_first.draw('latex')
ket_bell_third = 1/sqrt(2)*(Statevector.from_label('01') + Statevector.from_label('10'))
ket_bell_third.draw('latex')

<IPython.core.display.Latex object>

In [67]:
ket_bell_first.measure([0])

(np.str_('0'),
 Statevector([1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
             dims=(2, 2)))

In [78]:
Statevector.from_label('01').measure([1])

(np.str_('0'),
 Statevector([0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j],
             dims=(2, 2)))

In [83]:
ket_bell_first.data

array([0.70710678+0.j, 0.        +0.j, 0.        +0.j, 0.70710678+0.j])

In [84]:
Statevector.from_label('01').data

array([0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j])

In [91]:
from numpy import log2, mod
input_index = 1
index_measured = int(mod(log2(len(Statevector.from_label('01').data)) - input_index + 1, 2))
index_measured

0

In [116]:
def measure_qubit(state, qubit_index):
    input_index = qubit_index
    index_measured = int(mod(log2(len(state.data)) - input_index - 1, 2))
    return state.measure([index_measured])

In [120]:
measure_qubit(Statevector.from_label('001'), 0)

(np.str_('1'),
 Statevector([0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
              0.+0.j],
             dims=(2, 2, 2)))

In [125]:
[0] * 3
Statevector.from_label('001').measure([2])

(np.str_('0'),
 Statevector([0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
              0.+0.j],
             dims=(2, 2, 2)))

In [126]:
[0] * 3


[0, 0, 0]

In [128]:
import numpy as np
np.zeros(3)

array([0., 0., 0.])